Repository aquarist-labs/s3gw-ui, pull requests merged in 2022-10, with the labels that each got.

#71 UI: Login page does not show error messages
  CHANGELOG.md
  src/app/pages/login-page/login-page.component.html
  src/app/pages/login-page/login-page.component.ts
  src/app/shared/models/credentials.type.ts
  src/app/shared/services/api/auth.service.ts
  src/app/shared/services/http-error-interceptor.service.ts
Labels: bug

#72 Update links to website / forum
  src/app/shared/components/top-bar/top-bar.component.html
Labels: cleanup

#73 Display a dropdown icon in select controls.
  src/app/shared/components/declarative-form/declarative-form.component.html
  src/app/shared/components/declarative-form/declarative-form.component.scss
Labels: kind/enhancement

#75 Updated CHANGELOG.md with 0.7.0 release label
  CHANGELOG.md
Labels: kind/documentation

#76 ui: increase build budgets for prod
  angular.json
Labels: kind/bug

#78 Make the test workflow mandatory for PRs
  .github/workflows/test.yaml
  package.json
Labels: kind/enhancement

#79 Improve error messages when loading/saving fails.
  CHANGELOG.md
  src/app/functions.helper.ts
  src/app/pages/admin/bucket/bucket-form-page/bucket-form-page.component.html
  src/app/pages/admin/bucket/bucket-form-page/bucket-form-page.component.ts
  src/app/pages/admin/user/user-form-page/user-form-page.component.html
  src/app/pages/admin/user/user-form-page/user-form-page.component.ts
  src/app/pages/user/bucket/bucket-form-page/bucket-form-page.component.html
  src/app/pages/user/bucket/bucket-form-page/bucket-form-page.component.ts
Labels: kind/enhancement

#80 Update release date for 0.7.0
  CHANGELOG.md
Labels: kind/documentation

#82 Use eslint-plugin-prettier plugin to reduce conflicts between ESLint and Prettier.
  .eslintrc.json
  .prettierrc
  package-lock.json
  package.json
  src/app/shared/services/http-error-interceptor.service.ts
Labels: kind/enhancement

#83 Disable auto-reloading of datatable content …
  src/app/pages/admin/bucket/bucket-datatable-page/bucket-datatable-page.component.html
  src/app/pages/admin/user/user-datatable-page/user-datatable-page.component.html
  src/app/pages/user/bucket/bucket-datatable-page/bucket-datatable-page.component.html
Labels: kind/enhancement

#84 Trigger loadData once if auto-reloading is disabled.
  src/app/pages/user/object/object-datatable-page/object-datatable-page.component.spec.ts
  src/app/shared/components/datatable/datatable.component.ts
Labels: cleanup

#86 Fix table pagination issue.
  CHANGELOG.md
  src/app/shared/components/datatable/datatable.component.html
  src/app/shared/components/datatable/datatable.component.ts
Labels: kind/bug

#87 Refactor code and some small improvements.
  CHANGELOG.md
  proxy.conf.json.sample
  src/app/app.component.html
  src/app/app.component.spec.ts
  src/app/app.component.ts
  src/app/functions.helper.ts
  src/app/pages/admin/bucket/bucket-form-page/bucket-form-page.component.ts
  src/app/pages/admin/user/user-form-page/user-form-page.component.ts
  src/app/pages/shared/login-page/login-page.component.html
  src/app/pages/user/bucket/bucket-form-page/bucket-form-page.component.ts
  src/app/shared/components/alert-panel/alert-panel.component.html
  src/app/shared/components/alert-panel/alert-panel.component.scss
  src/app/shared/components/alert-panel/alert-panel.component.ts
  src/app/shared/components/top-bar/top-bar.component.html
  src/app/shared/components/top-bar/top-bar.component.ts
  src/app/shared/services/rgw-service-config.service.ts
Labels: kind/enhancement

#85 UI: Add ability to upload objects via browser
  CHANGELOG.md
  package-lock.json
  package.json
  src/app/pages/admin/user/user-key-datatable-page/user-key-datatable-page.component.ts
  src/app/pages/user/object/object-datatable-page/object-datatable-page.component.html
  src/app/pages/user/object/object-datatable-page/object-datatable-page.component.ts
  src/app/shared/enum/icon.enum.ts
  src/app/shared/services/api/s3-bucket.service.ts
  src/app/shared/services/api/s3-client.service.spec.ts
  src/app/shared/services/api/s3-client.service.ts
  src/app/shared/services/api/s3-user.service.ts
Labels: kind/enhancement

#88 UI: Add menu entry to download an object
  package-lock.json
  package.json
  src/app/pages/user/object/object-datatable-page/object-datatable-page.component.ts
  src/app/shared/enum/icon.enum.ts
  src/app/shared/services/api/s3-bucket.service.ts
Labels: kind/enhancement

#90 Update the title in the browser tab.
  src/app/shared/components/page-title/page-title.component.ts
Labels: kind/enhancement

#89 Display number of uploaded objects.
  src/app/pages/user/object/object-datatable-page/object-datatable-page.component.ts
Labels: kind/enhancement

#91 Replace 'translate' attribute directives by 'transloco'.
  src/app/pages/shared/not-found-page/not-found-page.component.html
  src/app/shared/components/top-bar/top-bar.component.html
Labels: kind/quality
