Repository aquarist-labs/s3gw-ui, pull requests merged in 2022-09, with the labels that each got.

#41 Add dashboard widget framework.
  CHANGELOG.md
  package-lock.json
  package.json
  src/app/dashboard/dashboard.module.ts
  src/app/dashboard/widgets/buckets-widget/buckets-widget.component.html
  src/app/dashboard/widgets/buckets-widget/buckets-widget.component.scss
  src/app/dashboard/widgets/buckets-widget/buckets-widget.component.spec.ts
  src/app/dashboard/widgets/buckets-widget/buckets-widget.component.ts
  src/app/dashboard/widgets/users-widget/users-widget.component.html
  src/app/dashboard/widgets/users-widget/users-widget.component.scss
  src/app/dashboard/widgets/users-widget/users-widget.component.spec.ts
  src/app/dashboard/widgets/users-widget/users-widget.component.ts
  src/app/pages/dashboard-page/dashboard-page.component.html
  src/app/pages/dashboard-page/dashboard-page.component.scss
  src/app/pages/dashboard-page/dashboard-page.component.spec.ts
  src/app/pages/pages.module.ts
  src/app/shared/components/components.module.ts
  src/app/shared/components/dashboard-widget/dashboard-widget.component.html
  src/app/shared/components/dashboard-widget/dashboard-widget.component.scss
  src/app/shared/components/dashboard-widget/dashboard-widget.component.spec.ts
  src/app/shared/components/dashboard-widget/dashboard-widget.component.ts
  src/app/shared/services/api/rgw.service.ts
  src/scss/bootstrap.scss
  src/scss/defaults/_colors.scss
Labels: enhancement

#45 UI: Add ability to navigate to specified URL when clicking a Dashboard widget.
  package-lock.json
  package.json
  src/app/dashboard/widgets/buckets-widget/buckets-widget.component.html
  src/app/dashboard/widgets/users-widget/users-widget.component.html
  src/app/shared/components/dashboard-widget/dashboard-widget.component.html
  src/app/shared/components/dashboard-widget/dashboard-widget.component.scss
  src/app/shared/components/dashboard-widget/dashboard-widget.component.ts
  src/styles.scss
Labels: enhancement

#46 Improve widget behaviour and look.
  src/app/shared/components/dashboard-widget/dashboard-widget.component.html
  src/app/shared/components/dashboard-widget/dashboard-widget.component.scss
Labels: enhancement

#47 Improve the widget data loading implementation.
  src/app/shared/components/dashboard-widget/dashboard-widget.component.scss
  src/app/shared/components/dashboard-widget/dashboard-widget.component.ts
Labels: enhancement

#48 Work-around a bug in Firefox where widgets are broken even if `break-inside: avoid` is set.
  src/app/pages/dashboard-page/dashboard-page.component.html
  src/app/pages/dashboard-page/dashboard-page.component.scss
  src/app/shared/components/dashboard-widget/dashboard-widget.component.scss
Labels: bug

#44 UI: Remove the bucket ID field in the bucker edit form
  src/app/pages/bucket/bucket-form-page/bucket-form-page.component.ts
Labels: enhancement

#49 Mock locale settings of Date.
  src/app/shared/pipes/locale-date.pipe.spec.ts
  src/app/shared/pipes/locale-date.pipe.ts
Labels: enhancement

#51 UI: Mark the user/bucket quota settings an non-functional
  CHANGELOG.md
  package-lock.json
  package.json
  src/app/dashboard/widgets/buckets-widget/buckets-widget.component.html
  src/app/dashboard/widgets/users-widget/users-widget.component.html
  src/app/pages/user/user-form-page/user-form-page.component.ts
  src/app/shared/components/dashboard-widget/dashboard-widget.component.html
  src/app/shared/components/declarative-form/declarative-form.component.html
  src/app/shared/components/declarative-form/declarative-form.component.scss
  src/app/shared/components/declarative-form/declarative-form.component.ts
  src/app/shared/models/declarative-form-config.type.ts
  src/scss/bootstrap.scss
Labels: enhancement

#52 Various improvements.
  src/app/pages/user/user-datatable-page/user-datatable-page.component.ts
  src/app/pages/user/user-form-page/user-form-page.component.ts
  src/app/shared/components/declarative-form/declarative-form.component.html
  src/app/shared/components/declarative-form/declarative-form.component.ts
  src/styles.scss
Labels: cleanup

#55 Use plural form for routes.
  src/app/app-routing.module.ts
  src/app/pages/bucket/bucket-datatable-page/bucket-datatable-page.component.ts
  src/app/pages/bucket/bucket-form-page/bucket-form-page.component.ts
  src/app/pages/user/user-datatable-page/user-datatable-page.component.ts
  src/app/pages/user/user-form-page/user-form-page.component.ts
  src/app/pages/user/user-key-datatable-page/user-key-datatable-page.component.ts
  src/app/pages/user/user-key-form-page/user-key-form-page.component.ts
  src/app/shared/components/breadcrumbs/breadcrumbs.component.ts
Labels: cleanup

#56 Fix various issues.
  src/app/dashboard/widgets/buckets-widget/buckets-widget.component.html
  src/app/dashboard/widgets/users-widget/users-widget.component.html
  src/app/pages/bucket/bucket-form-page/bucket-form-page.component.ts
  src/app/shared/components/navigation-bar/navigation-bar.component.ts
Labels: bug, cleanup

#54 Add support for bucket versioning
  CHANGELOG.md
  src/app/aws2.ts
  src/app/pages/bucket/bucket-form-page/bucket-form-page.component.ts
  src/app/shared/services/api/bucket.service.ts
  src/app/shared/services/api/rgw.service.ts
Labels: enhancement

#57 Various improvements.
  src/app/shared/models/credentials.type.ts
  src/app/shared/services/api/auth.service.ts
  src/app/shared/services/api/bucket.service.ts
  src/app/shared/services/api/rgw.service.ts
  src/app/shared/services/api/user.service.spec.ts
  src/app/shared/services/api/user.service.ts
  src/app/shared/services/auth-storage.service.ts
  src/app/shared/services/http-error-interceptor.service.ts
Labels: enhancement, cleanup

#58 UI: Add a title to the dashboard page
  src/app/pages/dashboard-page/dashboard-page.component.html
  src/app/shared/components/page-status/page-status.component.html
  src/app/shared/components/page-status/page-status.component.scss
Labels: cleanup

#59 UI: visual enhancements to dashboard cards
  src/app/shared/components/dashboard-widget/dashboard-widget.component.scss
  src/scss/defaults/_colors.scss
Labels: cleanup

#61 UI: Layout colour updates
  src/app/pages/dashboard-page/dashboard-page.component.html
  src/app/shared/components/navigation-bar/navigation-bar-item/navigation-bar-item.component.html
  src/app/shared/components/navigation-bar/navigation-bar-item/navigation-bar-item.component.scss
  src/app/shared/components/page-title/page-title.component.ts
  src/app/shared/components/top-bar/top-bar.component.scss
  src/app/shared/layouts/main-layout/main-layout.component.html
  src/app/shared/layouts/main-layout/main-layout.component.scss
  src/scss/defaults/_colors.scss
Labels: cleanup

#62 Use status colors specified in the Rancher UI kit.
  src/scss/defaults/_colors.scss
Labels: cleanup

#64 Fix import declaration.
  src/app/pages/bucket/bucket-form-page/bucket-form-page.component.ts
  src/app/pages/user/user-form-page/user-form-page.component.ts
  src/app/shared/components/modal/modal.component.ts
  src/app/shared/directives/autofocus.directive.ts
  src/app/shared/directives/dimless-binary.directive.ts
  src/app/shared/pipes/array.pipe.ts
Labels: cleanup

#63 UI: colour update to buttons
  CHANGELOG.md
  package-lock.json
  package.json
  src/app/pages/bucket/bucket-datatable-page/bucket-datatable-page.component.html
  src/app/pages/user/user-datatable-page/user-datatable-page.component.html
  src/app/shared/components/declarative-form/declarative-form.component.html
  src/app/shared/components/modal/modal.component.ts
  src/scss/bootstrap.scss
  src/scss/defaults/_colors.scss
  src/scss/ngx-toastr.scss
Labels: cleanup

#65 Adapt main layout.
  src/app/shared/components/navigation-bar/navigation-bar.component.html
  src/app/shared/components/top-bar/top-bar.component.html
  src/app/shared/components/top-bar/top-bar.component.scss
  src/app/shared/layouts/main-layout/main-layout.component.html
  src/app/shared/layouts/main-layout/main-layout.component.scss
Labels: cleanup

#66 UI: visual updates to tables
  src/app/dashboard/widgets/buckets-widget/buckets-widget.component.html
  src/app/dashboard/widgets/buckets-widget/buckets-widget.component.ts
  src/app/dashboard/widgets/users-widget/users-widget.component.html
  src/app/dashboard/widgets/users-widget/users-widget.component.ts
  src/app/pages/bucket/bucket-datatable-page/bucket-datatable-page.component.html
  src/app/pages/user/user-datatable-page/user-datatable-page.component.html
  src/app/pages/user/user-datatable-page/user-datatable-page.component.ts
  src/app/shared/components/dashboard-widget/dashboard-widget.component.scss
  src/app/shared/components/datatable/datatable.component.html
  src/app/shared/components/datatable/datatable.component.scss
  src/app/shared/components/navigation-bar/navigation-bar.component.ts
  src/app/shared/components/page-title/page-title.component.scss
  src/app/shared/components/top-bar/top-bar.component.html
  src/app/shared/components/top-bar/top-bar.component.scss
  src/app/shared/components/top-bar/top-bar.component.ts
  src/app/shared/enum/icon.enum.ts
  src/app/shared/layouts/main-layout/main-layout.component.scss
  src/scss/bootstrap.scss
  src/scss/defaults/_colors.scss
Labels: enhancement, cleanup

#67 Adapt table pagination.
  src/app/shared/components/datatable/datatable.component.html
  src/app/shared/components/datatable/datatable.component.scss
  src/scss/bootstrap.scss
Labels: cleanup

#53 ui: replace @angular/flex-layout by Bootstrap
  package-lock.json
  package.json
  src/app/pages/not-found-page/not-found-page.component.html
  src/app/pages/pages.module.ts
  src/app/shared/components/components.module.ts
  src/app/shared/components/declarative-form/declarative-form.component.html
  src/app/shared/components/navigation-bar/navigation-bar-item/navigation-bar-item.component.html
Labels: cleanup

#68 Adapt the login page to the Rancher look.
  src/app/i18n.helper.ts
  src/app/pages/login-page/login-page.component.html
  src/app/pages/login-page/login-page.component.scss
  src/app/pages/login-page/login-page.component.ts
  src/app/pages/pages.module.ts
  src/app/shared/components/language-button/language-button.component.html
  src/app/shared/components/language-button/language-button.component.ts
  src/app/shared/components/top-bar/top-bar.component.html
  src/assets/images/login-landscape.svg
Labels: enhancement, cleanup

#69 Adapt the key management page to the look of the rest of the UI.
  src/app/pages/user/user-datatable-page/user-datatable-page.component.ts
  src/app/pages/user/user-key-datatable-page/user-key-datatable-page.component.html
  src/app/pages/user/user-key-datatable-page/user-key-datatable-page.component.ts
  src/app/shared/components/page-status/page-status.component.scss
Labels: enhancement, cleanup

#42 UI: css refactoring to decrease bundle size
  angular.json
  src/app/pages/not-found-page/not-found-page.component.html
  src/app/pages/not-found-page/not-found-page.component.scss
  src/app/shared/components/alert-panel/alert-panel.component.html
  src/app/shared/components/alert-panel/alert-panel.component.scss
  src/app/shared/components/declarative-form/declarative-form.component.html
  src/app/shared/components/declarative-form/declarative-form.component.scss
  src/app/shared/components/modal/modal.component.html
  src/app/shared/components/modal/modal.component.scss
Labels: enhancement, DNM

#70 Adapt the datatable actions menu according to Rancher UI design kit.
  CHANGELOG.md
  src/app/shared/components/alert-panel/alert-panel.component.scss
  src/app/shared/components/datatable/datatable.component.html
  src/app/shared/components/datatable/datatable.component.scss
  src/app/shared/components/declarative-form/declarative-form.component.scss
  src/app/shared/enum/icon.enum.ts
Labels: enhancement, cleanup
