Repository aquarist-labs/s3gw-ui, pull requests merged in 2023-06, with the labels that each got.

#195 Add german translations
  src/frontend/src/app/shared/components/top-bar/top-bar.component.html
  src/frontend/src/assets/i18n/de_DE.json
Labels: kind/enhancement, area/ui

#193 User management cypress test
  src/frontend/cypress/e2e/user.cy.ts
  src/frontend/cypress/e2e/user.po.ts
Labels: area/ui

#196 Set default language in E2E tests
  src/frontend/cypress/e2e/bucket.cy.ts
  src/frontend/cypress/e2e/dashboard.cy.ts
  src/frontend/cypress/e2e/login.cy.ts
  src/frontend/cypress/e2e/topbar.cy.ts
  src/frontend/cypress/e2e/user.cy.ts
  src/frontend/src/app/shared/components/top-bar/top-bar.component.html
Labels: kind/enhancement, area/ui

#198 Hide `Last modified` column
  src/frontend/src/app/pages/admin/bucket/bucket-datatable-page/bucket-datatable-page.component.ts
Labels: kind/enhancement, area/ui

#197 UI: Add branding support
  src/frontend/angular.json
  src/frontend/package-lock.json
  src/frontend/package.json
  src/frontend/src/app/shared/components/block-ui/block-ui.component.scss
  src/frontend/src/app/shared/components/datatable/datatable.component.scss
  src/frontend/src/app/shared/components/navigation-bar/navigation-bar-item/navigation-bar-item.component.scss
  src/frontend/src/app/shared/components/navigation-bar/navigation-bar.component.scss
  src/frontend/src/app/shared/components/notification-bar/notification-bar.component.scss
  src/frontend/src/app/shared/components/top-bar/top-bar.component.html
  src/frontend/src/app/shared/components/top-bar/top-bar.component.scss
  src/frontend/src/app/shared/layouts/main-layout/main-layout.component.scss
  src/frontend/src/scss/bootstrap.scss
  src/frontend/src/scss/defaults/_index.scss
  src/frontend/src/scss/ngx-toastr.scss
  src/frontend/src/scss/themes/default/theme/_colors.scss
  src/frontend/src/scss/themes/default/theme/_fonts.scss
  src/frontend/src/scss/themes/default/theme/_index.scss
  src/frontend/src/scss/themes/default/theme/_variables.scss
  src/frontend/src/scss/themes/longhorn/theme/_colors.scss
  src/frontend/src/scss/themes/longhorn/theme/_fonts.scss
  src/frontend/src/scss/themes/longhorn/theme/_index.scss
  src/frontend/src/scss/themes/longhorn/theme/_variables.scss
  src/frontend/src/scss/vendor/_colors.scss
  src/frontend/src/scss/vendor/_fonts.scss
  src/frontend/src/scss/vendor/_index.scss
  src/frontend/src/scss/vendor/_variables.scss
  src/frontend/src/styles.scss
Labels: kind/enhancement, area/ui

#199 UI: Search button only performs a search on a page level
  CHANGELOG.md
  src/frontend/src/app/shared/components/datatable/datatable.component.ts
Labels: kind/bug, area/ui

#200 UI: The datatable pagination does not show the correct number of displayed items
  CHANGELOG.md
  src/frontend/src/app/shared/components/datatable/datatable.component.html
  src/frontend/src/app/shared/components/datatable/datatable.component.spec.ts
  src/frontend/src/app/shared/components/datatable/datatable.component.ts
Labels: kind/bug, area/ui

#192 cypress test for bucket management
  src/frontend/cypress/e2e/bucket.cy.ts
  src/frontend/cypress/e2e/bucket.po.ts
Labels: area/ui

#203 Cleanup code
  src/frontend/src/app/functions.helper.spec.ts
  src/frontend/src/app/functions.helper.ts
  src/frontend/src/app/pages/user/object/object-datatable-page/object-datatable-page.component.ts
Labels: kind/quality, area/ui

#201 Enhance theming capability
  CHANGELOG.md
  src/frontend/angular.json
  src/frontend/package-lock.json
  src/frontend/package.json
  src/frontend/src/app/app.component.spec.ts
  src/frontend/src/app/app.component.ts
  src/frontend/src/app/app.module.ts
  src/frontend/src/app/i18n.helper.ts
  src/frontend/src/app/pages/shared/login-page/login-page.component.html
  src/frontend/src/app/pages/shared/login-page/login-page.component.ts
  src/frontend/src/app/pages/user/object/object-datatable-page/object-datatable-page.component.ts
  src/frontend/src/app/shared/components/datatable/datatable.component.html
  src/frontend/src/app/shared/components/page-title/page-title.component.ts
  src/frontend/src/app/shared/components/top-bar/top-bar.component.html
  src/frontend/src/app/shared/components/top-bar/top-bar.component.ts
  src/frontend/src/app/shared/services/app-config.service.spec.ts
  src/frontend/src/app/shared/services/app-config.service.ts
  src/frontend/src/app/shared/services/rxjs-ui-helper.service.ts
  src/frontend/src/app/transloco-root.module.ts
  src/frontend/src/assets/i18n/de_DE.json
  src/frontend/src/index.html
  src/frontend/src/scss/bootstrap.scss
  src/frontend/src/scss/themes/longhorn/theme/_fonts.scss
  src/frontend/src/scss/themes/longhorn/theme/_variables.scss
  src/frontend/src/vendor/default/assets/app.config.json
  src/frontend/src/vendor/default/assets/images/logo-transparent.svg
  src/frontend/src/vendor/default/assets/images/logo.svg
  src/frontend/src/vendor/default/favicon.ico
  src/frontend/src/vendor/default/favicon.svg
  src/frontend/src/vendor/default/favicon_180x180.png
  src/frontend/src/vendor/default/scss/theme/_colors.scss
  src/frontend/src/vendor/default/scss/theme/_fonts.scss
  src/frontend/src/vendor/default/scss/theme/_index.scss
  src/frontend/src/vendor/default/scss/theme/_variables.scss
  src/frontend/src/vendor/longhorn/assets/app.config.json
  src/frontend/src/vendor/longhorn/assets/images/logo.svg
  src/frontend/src/vendor/longhorn/favicon.ico
  src/frontend/src/vendor/longhorn/favicon.svg
  src/frontend/src/vendor/longhorn/favicon_180x180.png
  src/frontend/src/vendor/longhorn/scss/theme/_colors.scss
  src/frontend/src/vendor/longhorn/scss/theme/_fonts.scss
  src/frontend/src/vendor/longhorn/scss/theme/_index.scss
  src/frontend/src/vendor/longhorn/scss/theme/_variables.scss
Labels: kind/enhancement, area/ui

#205 UI: Prevent the restoring of the deleted object version
  CHANGELOG.md
  src/frontend/src/app/pages/user/object/object-version-datatable-page/object-version-datatable-page.component.ts
Labels: kind/bug, area/ui

#204 UI: Improve object deletion
  CHANGELOG.md
  src/frontend/src/app/pages/admin/bucket/bucket-datatable-page/bucket-datatable-page.component.ts
  src/frontend/src/app/pages/admin/user/user-datatable-page/user-datatable-page.component.ts
  src/frontend/src/app/pages/admin/user/user-key-datatable-page/user-key-datatable-page.component.ts
  src/frontend/src/app/pages/shared/bucket/bucket-lifecycle-datatable-page/bucket-lifecycle-datatable-page.component.ts
  src/frontend/src/app/pages/user/bucket/bucket-datatable-page/bucket-datatable-page.component.ts
  src/frontend/src/app/pages/user/object/object-datatable-page/object-datatable-page.component.ts
  src/frontend/src/app/shared/components/declarative-form-modal/declarative-form-modal.component.html
  src/frontend/src/app/shared/components/declarative-form-modal/declarative-form-modal.component.scss
  src/frontend/src/app/shared/components/declarative-form/declarative-form.component.html
  src/frontend/src/app/shared/components/submit-button/submit-button.component.html
  src/frontend/src/app/shared/components/submit-button/submit-button.component.ts
  src/frontend/src/app/shared/models/declarative-form-modal-config.type.ts
  src/frontend/src/app/shared/services/api/s3-bucket.service.ts
  src/frontend/src/app/shared/services/modal-dialog.service.ts
  src/frontend/src/styles.scss
Labels: kind/enhancement, area/ui

#210 .github: add backend codecov coverage report
  .github/workflows/test.yaml
Labels: area/CI

#202 Improvements on bucket cypress test
  src/frontend/cypress/e2e/bucket.cy.ts
  src/frontend/cypress/e2e/bucket.po.ts
  src/frontend/cypress/e2e/page-helper.po.ts
  src/frontend/cypress/e2e/user.cy.ts
  src/frontend/cypress/e2e/user.po.ts
  src/frontend/cypress/fixtures/example.json
  src/frontend/cypress/support/commands.ts
  src/frontend/package-lock.json
  src/frontend/package.json
Labels: area/ui

#212 Disable download button for deleted objects
  CHANGELOG.md
  src/frontend/src/app/pages/user/object/object-datatable-page/object-datatable-page.component.ts
Labels: kind/bug, area/ui

#211 s3gw-ui: add README.md
  README.md
Labels: kind/documentation, area/ui

#208 backend: add admin ops (skeleton) support
  src/backend/admin_ops/__init__.py
  src/backend/admin_ops/buckets.py
  src/backend/admin_ops/errors.py
  src/backend/admin_ops/types.py
  src/backend/admin_ops/users.py
  src/backend/s3gw/__init__.py
  src/backend/s3gw/client.py
  src/backend/s3gw/errors.py
  src/backend/tests/admin_ops/test_admin_ops.py
  src/backend/tests/admin_ops/test_buckets.py
  src/backend/tests/admin_ops/test_errors.py
  src/backend/tests/admin_ops/test_types.py
  src/backend/tests/admin_ops/test_users.py
  src/requirements-dev.txt
  src/requirements.txt
Labels: kind/feature, area/ui
