Repository aquarist-labs/s3gw-ui, pull requests merged in 2023-10, with the labels that each got.

#269 backend/admin_ops: don't verify certs on send request
  src/backend/admin_ops/__init__.py
Labels: kind/bug, area/ui

#268 Disable caching of index.html
  src/backend/tests/unit/test_app.py
  src/s3gw_ui_backend.py
Labels: kind/enhancement, area/ui

#271 Inconsistent restore behavior
  CHANGELOG.md
  src/frontend/src/app/pages/user/object/object-version-datatable-page/object-version-datatable-page.component.ts
Labels: kind/bug, area/ui

#272 Update NPM packages
  src/frontend/package-lock.json
  src/frontend/package.json
Labels: kind/quality, area/ui

#274 Dockerfile: pin base image to python3.11
  src/Dockerfile
  src/backend/api/buckets.py
  src/backend/api/objects.py
  src/tox.ini
Labels: kind/bug, area/containers, area/ui

#275 Makefile: make running backend more resilient
  Makefile
Labels: kind/quality, area/ui

#279 Allow the deletion of specific object versions
  CHANGELOG.md
  src/frontend/src/app/pages/user/object/object-version-datatable-page/object-version-datatable-page.component.ts
Labels: kind/enhancement, area/ui

#276 readme: fix typos
  README.md
  src/backend/README.md
Labels: kind/documentation, kind/quality, area/ui

#277 longhorn integration: subpath support
  .github/workflows/test.yaml
  .gitignore
  src/Dockerfile
  src/backend/config.py
  src/backend/tests/unit/test_app.py
  src/backend/tests/unit/test_config.py
  src/s3gw_ui_backend.py
Labels: kind/feature, area/ui, priority/0

#278 Make explicit description for default retention for buckets
  src/frontend/src/app/pages/admin/bucket/bucket-form-page/bucket-form-page.component.ts
  src/frontend/src/app/pages/user/bucket/bucket-form-page/bucket-form-page.component.ts
Labels: kind/quality, area/ui

#281 Catch REST API errors
  CHANGELOG.md
  src/backend/api/__init__.py
  src/backend/tests/unit/api/test_api.py
  src/frontend/src/app/shared/services/api/s3-bucket.service.ts
Labels: kind/bug, area/ui

#282 Adapt error handling in S3 services
  src/frontend/src/app/shared/services/api/s3-bucket.service.ts
Labels: kind/quality, area/ui
