Repository aquarist-labs/s3gw-ui, pull requests merged in 2023-09, with the labels that each got.

#242 backend: obtain 's3gw' service address via env variable
  src/Dockerfile
  src/backend/api/__init__.py
  src/backend/api/admin.py
  src/backend/api/buckets.py
  src/backend/api/config.py
  src/backend/config.py
  src/backend/tests/unit/api/test_api.py
  src/backend/tests/unit/api/test_api_config.py
  src/backend/tests/unit/test_config.py
  src/frontend/src/app/shared/services/api/s3gw-api.service.ts
  src/frontend/src/app/shared/services/s3gw-config.service.spec.ts
  src/frontend/src/app/shared/services/s3gw-config.service.ts
  src/frontend/src/assets/rgw_service.config.json.sample
  src/s3gw_ui_backend.py
Labels: kind/feature, area/ui

#256 Update changelog
  CHANGELOG.md
Labels: kind/quality, area/ui

#258 Cleanup code
  src/frontend/package-lock.json
  src/frontend/package.json
  src/frontend/proxy.conf.json.sample
  src/frontend/src/app/app.component.html
  src/frontend/src/app/app.component.ts
  src/frontend/src/app/app.module.ts
  src/frontend/src/app/shared/services/api/admin-ops-bucket.service.spec.ts
  src/frontend/src/app/shared/services/api/admin-ops-user.service.spec.ts
  src/frontend/src/app/shared/services/api/auth.service.spec.ts
  src/frontend/src/app/shared/services/api/s3-user.service.spec.ts
  src/frontend/src/app/shared/services/api/s3gw-api.service.ts
  src/frontend/src/app/shared/services/s3gw-config.service.ts
Labels: kind/quality, area/ui

#259 Improve error handling
  src/backend/api/__init__.py
  src/backend/api/buckets.py
  src/backend/tests/unit/api/test_api.py
  src/backend/tests/unit/api/test_api_buckets.py
Labels: kind/quality, area/ui

#260 Add more unit tests to increase code coverage
  src/backend/config.py
  src/backend/tests/unit/test_config.py
Labels: kind/quality, area/ui

#261 Upgrade Bootstrap package
  src/frontend/package-lock.json
  src/frontend/package.json
Labels: kind/quality, area/ui

#262 Disable `Update` button if form is pristine
  src/frontend/src/app/pages/user/object/object-datatable-page/object-datatable-page.component.ts
  src/frontend/src/app/shared/components/declarative-form/declarative-form.component.ts
  src/frontend/src/app/shared/models/declarative-form-config.type.ts
Labels: kind/enhancement, area/ui

#263 Error when deleting an object with legal hold
  src/backend/api/objects.py
  src/backend/tests/unit/api/test_api_objects.py
Labels: kind/bug, area/ui

#265 Relocate `cypress-file-upload`into the right dependency list
  src/frontend/package-lock.json
  src/frontend/package.json
Labels: kind/bug, area/ui

#267 Dropdown buttons are not rendered correct
  CHANGELOG.md
  src/frontend/src/app/shared/components/top-bar/top-bar.component.scss
  src/frontend/src/vendor/default/scss/theme/_index.scss
  src/frontend/src/vendor/longhorn/scss/theme/_colors.scss
  src/frontend/src/vendor/longhorn/scss/theme/_index.scss
  src/frontend/src/vendor/rancher/scss/theme/_index.scss
Labels: kind/bug, area/ui
