Repository aquarist-labs/s3gw-ui, pull requests merged in 2023-07, with the labels that each got.

#217 Update NPM packages
  src/frontend/package-lock.json
  src/frontend/package.json
Labels: kind/quality, area/ui

#216 Adapt API to existing TS code
  src/backend/admin_ops/buckets.py
  src/backend/api/__init__.py
  src/backend/api/bucket.py
  src/backend/tests/api/test_bucket.py
  src/requirements.txt
Labels: kind/enhancement, area/ui

#215 UI: Do not close datatable column menu on inside clicks
  CHANGELOG.md
  src/frontend/src/app/shared/components/datatable/datatable.component.html
Labels: kind/bug, area/ui

#214 Add a hint for the prefix field in the lifecycle rule dialog
  CHANGELOG.md
  src/frontend/src/app/pages/shared/bucket/bucket-lifecycle-datatable-page/bucket-lifecycle-datatable-page.component.ts
Labels: kind/enhancement, area/ui

#218 UI: The user full name does not allow blanks
  src/frontend/src/app/pages/admin/user/user-form-page/user-form-page.component.ts
Labels: kind/bug, area/ui

#224 use s3gw backend with CI's tests
  .github/workflows/test.yaml
  test-env/cluster-prepare.sh
Labels: area/CI, area/tests, area/ui

#221 Test: user full name allows blanks and special characters
  src/frontend/cypress/e2e/user.cy.ts
Labels: area/ui

#219 Improvement on user and bucket test and addition of administration test
  src/frontend/cypress/e2e/admin.cy.ts
  src/frontend/cypress/e2e/bucket.cy.ts
  src/frontend/cypress/e2e/bucket.po.ts
  src/frontend/cypress/e2e/object.po.ts
  src/frontend/cypress/e2e/user.cy.ts
  src/frontend/cypress/e2e/user.po.ts
Labels: area/ui

#227 add patch-ui-deployment task in Makefile
  Makefile
  src/backend/README.md
  test-env/patch-ui-deployment.sh
Labels: kind/enhancement, area/kubernetes

#228 change style of endpoints from camel case to dash
  src/backend/api/admin.py
  src/backend/api/bucket.py
Labels: kind/quality, area/ui

#226 add a set of admin-bucket-api endpoints
  src/backend/admin_ops/buckets.py
  src/backend/api/admin.py
  src/backend/tests/admin_ops/test_admin_ops.py
Labels: kind/enhancement, area/ui

#230 improve test quality
  src/backend/tests/admin_ops/test_admin_ops.py
  src/backend/tests/api/test_bucket.py
Labels: kind/quality, area/tests

#233 Update NPM packages
  src/frontend/package-lock.json
  src/frontend/package.json
Labels: kind/quality, area/ui

#234 Table header breaks on zoom-in
  CHANGELOG.md
  src/frontend/src/app/shared/components/datatable/datatable.component.ts
  src/frontend/src/app/shared/models/datatable-column.type.ts
Labels: kind/bug, area/ui

#232 backend: add flake8 linting and pre-commit hooks
  .gitignore
  .pre-commit-config.yaml
  pre-commit-check-pyright.sh
  src/.flake8
  src/backend/api/__init__.py
  src/backend/api/bucket.py
  src/backend/s3gw/client.py
  src/backend/tests/admin_ops/test_admin_ops.py
  src/backend/tests/admin_ops/test_types.py
  src/backend/tests/admin_ops/test_users.py
  src/backend/tests/api/test_bucket.py
  src/backend/tests/conftest.py
  src/backend/tests/mock_server.py
  src/backend/tests/moto_server.py
  src/pyproject.toml
  src/requirements-dev.txt
  src/tox.ini
Labels: kind/quality

#236 UI: Add admin checkbox to user create/edit dialog
  CHANGELOG.md
  src/backend/admin_ops/types.py
  src/frontend/src/app/pages/admin/user/user-datatable-page/user-datatable-page.component.ts
  src/frontend/src/app/pages/admin/user/user-form-page/user-form-page.component.ts
  src/frontend/src/app/shared/services/api/admin-ops-user.service.spec.ts
  src/frontend/src/app/shared/services/api/admin-ops-user.service.ts
Labels: kind/enhancement, area/ui

#235 UI: Remove the scroll option from the data table head
  CHANGELOG.md
  src/frontend/src/app/shared/components/datatable/datatable.component.html
Labels: kind/bug, area/ui

#231 Data table test on bucket and object
  src/frontend/cypress/e2e/bucket.cy.ts
  src/frontend/cypress/e2e/bucket.po.ts
  src/frontend/cypress/e2e/object.po.ts
  src/frontend/cypress/e2e/page-helper.po.ts
  src/frontend/cypress/e2e/user.cy.ts
  src/frontend/cypress/support/commands.ts
Labels: area/tests, area/ui

#229 S3 endpoints 1
  src/backend/api/bucket.py
  src/backend/api/types.py
  src/backend/tests/api/test_api_types.py
  src/backend/tests/api/test_bucket.py
  src/tox.ini
Labels: kind/enhancement, area/ui

#238 Refactor bucket deletion dialog in `Administrator` mode
  src/frontend/cypress/e2e/bucket.cy.ts
  src/frontend/cypress/e2e/object.po.ts
  src/frontend/cypress/e2e/page-helper.po.ts
  src/frontend/src/app/pages/admin/bucket/bucket-datatable-page/bucket-datatable-page.component.ts
  src/frontend/src/app/pages/user/object/object-datatable-page/object-datatable-page.component.ts
  src/frontend/src/app/shared/services/modal-dialog.service.ts
Labels: kind/enhancement, area/ui

#240 Several improvements and make the UI backend API RESTful
  src/backend/admin_ops/buckets.py
  src/backend/admin_ops/users.py
  src/backend/api/admin.py
  src/backend/api/buckets.py
  src/backend/tests/admin_ops/test_admin_ops.py
  src/backend/tests/admin_ops/test_buckets.py
  src/backend/tests/admin_ops/test_users.py
  src/backend/tests/api/test_api_buckets.py
  src/s3gw_ui_backend.py
Labels: kind/quality, area/ui
