Repository aquarist-labs/s3gw-ui, pull requests merged in 2023-04, with the labels that each got.

#161 Use correct component name
  src/app/pages/admin/bucket/bucket-datatable-page/bucket-datatable-page.component.html
  src/app/pages/admin/bucket/bucket-form-page/bucket-form-page.component.html
  src/app/pages/admin/dashboard-page/dashboard-page.component.html
  src/app/pages/admin/user/user-datatable-page/user-datatable-page.component.html
  src/app/pages/admin/user/user-form-page/user-form-page.component.html
  src/app/pages/admin/user/user-key-datatable-page/user-key-datatable-page.component.html
  src/app/pages/admin/user/user-key-form-page/user-key-form-page.component.html
  src/app/pages/shared/bucket/bucket-lifecycle-datatable-page/bucket-lifecycle-datatable-page.component.html
  src/app/pages/user/bucket/bucket-datatable-page/bucket-datatable-page.component.html
  src/app/pages/user/bucket/bucket-form-page/bucket-form-page.component.html
  src/app/pages/user/dashboard-page/dashboard-page.component.html
  src/app/pages/user/object/object-datatable-page/object-datatable-page.component.html
  src/app/shared/components/page-wrapper/page-wrapper.component.ts
Labels: kind/quality, area/ui

#162 Configure bootstrap and let it populate the body element
  src/scss/bootstrap.scss
  src/styles.scss
Labels: kind/quality, area/ui

#157 Create bucket using AWS SDK
  src/app/shared/services/api/s3-bucket.service.ts
Labels: kind/quality, area/ui

#123 UI: Add feature to manage object tags
  CHANGELOG.md
  package-lock.json
  package.json
  src/app/pages/user/object/object-datatable-page/object-datatable-page.component.ts
  src/app/shared/components/declarative-form/declarative-form.component.ts
  src/app/shared/components/tags-input/tags-input.component.ts
  src/app/shared/models/declarative-form-config.type.ts
  src/app/shared/services/rxjs-ui-helper.service.ts
Labels: kind/feature, area/ui

#160 Add hint to `Expires after` form field
  src/app/pages/shared/bucket/bucket-lifecycle-datatable-page/bucket-lifecycle-datatable-page.component.ts
Labels: kind/enhancement, area/ui

#163 Cleanup datatable code
  src/app/pages/user/object/object-datatable-page/object-datatable-page.component.html
  src/app/shared/components/components.module.ts
  src/app/shared/components/datatable-custom-top/datatable-custom-top.component.spec.ts
  src/app/shared/components/datatable-custom-top/datatable-custom-top.component.ts
  src/app/shared/components/datatable-secondary-header/datatable-secondary-header.component.html
  src/app/shared/components/datatable-secondary-header/datatable-secondary-header.component.scss
  src/app/shared/components/datatable-secondary-header/datatable-secondary-header.component.spec.ts
  src/app/shared/components/datatable-secondary-header/datatable-secondary-header.component.ts
  src/app/shared/components/datatable/datatable.component.html
  src/app/shared/components/datatable/datatable.component.scss
Labels: kind/quality, area/ui

#169 Increase z-index of the notification sidebar
  src/frontend/src/app/shared/layouts/main-layout/main-layout.component.scss
Labels: kind/bug, area/ui

#170 Object Locks - legal hold don't prevent deletion
  src/frontend/package-lock.json
  src/frontend/package.json
  src/frontend/src/app/pages/admin/bucket/bucket-datatable-page/bucket-datatable-page.component.ts
  src/frontend/src/app/pages/admin/user/user-datatable-page/user-datatable-page.component.ts
  src/frontend/src/app/pages/admin/user/user-key-datatable-page/user-key-datatable-page.component.ts
  src/frontend/src/app/pages/shared/bucket/bucket-lifecycle-datatable-page/bucket-lifecycle-datatable-page.component.ts
  src/frontend/src/app/pages/user/bucket/bucket-datatable-page/bucket-datatable-page.component.ts
  src/frontend/src/app/pages/user/object/object-datatable-page/object-datatable-page.component.html
  src/frontend/src/app/pages/user/object/object-datatable-page/object-datatable-page.component.ts
  src/frontend/src/app/shared/components/datatable-actions/datatable-actions.component.ts
  src/frontend/src/app/shared/components/declarative-form/declarative-form.component.html
  src/frontend/src/app/shared/components/declarative-form/declarative-form.component.ts
  src/frontend/src/app/shared/components/submit-button/submit-button.component.html
  src/frontend/src/app/shared/components/submit-button/submit-button.component.ts
  src/frontend/src/app/shared/enum/icon.enum.ts
  src/frontend/src/app/shared/layouts/main-layout/main-layout.component.scss
  src/frontend/src/app/shared/models/datatable-action.type.ts
  src/frontend/src/app/shared/models/declarative-form-config.type.ts
  src/frontend/src/app/shared/services/api/s3-bucket.service.ts
  src/frontend/src/scss/bootstrap.scss
Labels: kind/bug, area/ui

#165 ui: add backend
  .github/workflows/test.yaml
  src/.coveragerc
  src/.gitignore
  src/backend/README.md
  src/backend/__init__.py
  src/backend/api/__init__.py
  src/backend/api/bucket.py
  src/backend/logging.py
  src/backend/tests/api/test_api.py
  src/backend/tests/api/test_bucket.py
  src/backend/tests/conftest.py
  src/backend/tests/mock_server.py
  src/backend/tests/moto_server.py
  src/backend/tests/test_logging.py
  src/pyproject.toml
  src/requirements-dev.txt
  src/requirements.txt
  src/s3gw_ui_backend.py
  src/tox.ini
  src/typings/aiobotocore/session.pyi
Labels: kind/feature, area/ui

#172 UI: Validate access key
  src/frontend/src/app/pages/admin/user/user-key-form-page/user-key-form-page.component.ts
Labels: kind/enhancement, area/ui

#173 Validate user ID and name
  src/frontend/src/app/pages/admin/user/user-form-page/user-form-page.component.ts
Labels: kind/enhancement, area/ui
