Repository aquarist-labs/s3gw-ui, pull requests merged in 2023-11, with the labels that each got.

#283 Fix validation error for `DeletedObject`
  src/backend/api/types.py
Labels: kind/bug, area/ui

#284 Update changelog
  CHANGELOG.md
Labels: kind/documentation, area/ui

#285 Add support for configuring S3 addressing style
  CHANGELOG.md
  src/backend/api/__init__.py
  src/backend/config.py
  src/backend/tests/unit/api/test_api.py
  src/backend/tests/unit/conftest.py
  src/backend/tests/unit/helpers.py
  src/backend/tests/unit/test_config.py
Labels: kind/enhancement, area/ui

#286 Instance Identification
  src/backend/api/config.py
  src/backend/api/objects.py
  src/backend/config.py
  src/backend/logging.py
  src/backend/tests/unit/api/test_api_config.py
  src/backend/tests/unit/test_app.py
  src/backend/tests/unit/test_config.py
  src/backend/tests/unit/test_logging.py
  src/frontend/src/app/app.module.ts
  src/frontend/src/app/pages/shared/login-page/login-page.component.ts
  src/frontend/src/app/shared/components/top-bar/top-bar.component.html
  src/frontend/src/app/shared/components/top-bar/top-bar.component.ts
  src/frontend/src/app/shared/forms/validators.ts
  src/frontend/src/app/shared/pipes/basename.pipe.spec.ts
  src/frontend/src/app/shared/pipes/basename.pipe.ts
  src/frontend/src/app/shared/services/api/s3-bucket.service.ts
  src/frontend/src/app/shared/services/api/s3gw-api.service.spec.ts
  src/frontend/src/app/shared/services/api/s3gw-api.service.ts
  src/frontend/src/app/shared/services/app-main-config.service.spec.ts
  src/frontend/src/app/shared/services/app-main-config.service.ts
  src/frontend/src/app/shared/services/s3gw-config.service.ts
  src/frontend/src/vendor/longhorn/assets/app.config.json
  src/s3gw_ui_backend.py
Labels: kind/feature, area/ui, priority/1

#288 Update NPM packages
  src/frontend/package-lock.json
  src/frontend/package.json
Labels: kind/quality, area/ui

#289 Deleting a not empty bucket displays a misleading error
  src/backend/api/__init__.py
  src/backend/tests/unit/api/test_api.py
Labels: kind/bug, area/ui, backport

#290 Deleting a not empty bucket displays a misleading error
  src/backend/api/__init__.py
  src/backend/tests/unit/api/test_api.py
Labels: kind/bug, area/ui

#294 Deleting a not empty bucket displays a misleading error
  src/frontend/src/app/pages/user/object/object-datatable-page/object-datatable-page.component.ts
Labels: area/ui, backport

#293 Handle upload errors correctly
  src/frontend/src/app/pages/user/object/object-datatable-page/object-datatable-page.component.ts
Labels: kind/enhancement, area/ui

#295 Deleting an object deletes all following the same name base pattern
  src/backend/api/objects.py
  src/backend/api/types.py
  src/backend/tests/unit/api/test_api_objects.py
  src/frontend/src/app/pages/user/object/object-datatable-page/object-datatable-page.component.ts
  src/frontend/src/app/shared/services/api/s3-bucket.service.ts
Labels: kind/bug, area/ui, priority/0

#296 Deleting an object deletes all following the same name base pattern
  src/backend/api/objects.py
  src/backend/api/types.py
  src/backend/tests/unit/api/test_api_objects.py
  src/frontend/src/app/pages/user/object/object-datatable-page/object-datatable-page.component.ts
  src/frontend/src/app/shared/services/api/s3-bucket.service.ts
Labels: kind/bug, area/ui, backport

#297 fix: ui path validation
  Makefile
  src/backend/config.py
  src/backend/tests/unit/test_config.py
Labels: kind/bug, area/ui, priority/0

#299 UI: The prefix handling is buggy at several places in the REST API
  src/backend/api/objects.py
  src/backend/api/types.py
  src/backend/tests/unit/api/test_api_objects.py
  src/frontend/src/app/pages/user/object/object-version-datatable-page/object-version-datatable-page.component.ts
  src/frontend/src/app/pages/user/user-pages-routing.module.ts
  src/frontend/src/app/shared/services/api/s3-bucket.service.ts
Labels: kind/bug, area/ui

#300 UI: The prefix handling is buggy at several places in the REST API
  src/backend/api/objects.py
  src/backend/api/types.py
  src/backend/tests/unit/api/test_api_objects.py
  src/frontend/src/app/pages/user/object/object-version-datatable-page/object-version-datatable-page.component.ts
  src/frontend/src/app/pages/user/user-pages-routing.module.ts
  src/frontend/src/app/shared/services/api/s3-bucket.service.ts
Labels: kind/bug, area/ui, backport

#305 UI: Transloco configuration is missing a fallback language
  CHANGELOG.md
  src/frontend/src/app/i18n.helper.ts
  src/frontend/src/app/transloco-root.module.ts
Labels: kind/bug, area/ui
