Repository aquarist-labs/s3gw-ui, pull requests merged in 2023-08, with the labels that each got.

#241 backend: make unit tests not rely on external entities
  .github/workflows/test.yaml
  src/backend/admin_ops/__init__.py
  src/backend/api/buckets.py
  src/backend/tests/conftest.py
  src/backend/tests/functional/test_api.py
  src/backend/tests/mock_server.py
  src/backend/tests/unit/admin_ops/test_admin_ops.py
  src/backend/tests/unit/admin_ops/test_buckets.py
  src/backend/tests/unit/admin_ops/test_errors.py
  src/backend/tests/unit/admin_ops/test_types.py
  src/backend/tests/unit/admin_ops/test_users.py
  src/backend/tests/unit/api/test_api.py
  src/backend/tests/unit/api/test_api_admin.py
  src/backend/tests/unit/api/test_api_buckets.py
  src/backend/tests/unit/api/test_api_types.py
  src/backend/tests/unit/conftest.py
  src/backend/tests/unit/moto_server.py
  src/backend/tests/unit/test_logging.py
  src/tox.ini
Labels: kind/quality, area/tests

#244 UI: Creating new keys fails when the keys are manually specified
  CHANGELOG.md
  src/frontend/src/app/shared/services/api/admin-ops-user.service.ts
Labels: kind/bug, area/ui

#239 S3 endpoints 3
  src/backend/api/objects.py
  src/backend/api/types.py
  src/backend/tests/unit/api/test_api_buckets.py
  src/backend/tests/unit/api/test_api_objects.py
  src/s3gw_ui_backend.py
Labels: kind/enhancement, DNM, area/ui

#245 Add helper to mock S3 API calls
  src/backend/tests/unit/api/test_api_buckets.py
  src/backend/tests/unit/api/test_api_objects.py
  src/backend/tests/unit/helpers.py
Labels: kind/quality, area/ui

#250 ci: Add quay expiry labels
  src/frontend/Dockerfile
Labels: area/containers, area/CI

#246 [Test]: Notification tests on bucket and object
  src/frontend/cypress/e2e/notification.cy.ts
  src/frontend/cypress/e2e/notification.po.ts
Labels: area/ui

#243 [Test]: Language validation test
  src/frontend/cypress/e2e/language.cy.ts
  src/frontend/cypress/e2e/language.po.ts
Labels: area/ui

#248 Various improvements
  src/backend/api/__init__.py
  src/backend/api/buckets.py
  src/backend/tests/unit/api/test_api_buckets.py
Labels: kind/quality, area/ui

#251 Add more API endpoints related to bucket objects
  .gitignore
  src/backend/api/__init__.py
  src/backend/api/buckets.py
  src/backend/api/objects.py
  src/backend/api/types.py
  src/backend/tests/unit/api/test_api_buckets.py
  src/backend/tests/unit/api/test_api_objects.py
  src/requirements.txt
Labels: kind/enhancement, area/ui

#253 Do not restore latest object version
  CHANGELOG.md
  src/frontend/src/app/pages/user/object/object-version-datatable-page/object-version-datatable-page.component.ts
Labels: kind/quality, area/ui
