Repository aquarist-labs/s3gw-ui, pull requests merged in 2023-05, with the labels that each got.

#175 Update Angular + other NPM packages
  src/frontend/package-lock.json
  src/frontend/package.json
Labels: kind/quality, area/ui

#176 UI: Improve pattern form validator
  src/frontend/src/app/pages/admin/user/user-form-page/user-form-page.component.ts
  src/frontend/src/app/pages/admin/user/user-key-form-page/user-key-form-page.component.ts
  src/frontend/src/app/shared/components/declarative-form/declarative-form.component.html
  src/frontend/src/app/shared/models/declarative-form-config.type.ts
Labels: kind/enhancement, area/ui

#178 UI: Remove the user/bucket quota settings in the create/edit user page
  src/frontend/src/app/pages/admin/user/user-form-page/user-form-page.component.ts
Labels: kind/quality, area/ui

#179 UI: Replace ng-block-ui library to be able to upgrade Angular
  src/frontend/package-lock.json
  src/frontend/package.json
  src/frontend/src/app/app.component.html
  src/frontend/src/app/pages/admin/bucket/bucket-datatable-page/bucket-datatable-page.component.ts
  src/frontend/src/app/pages/admin/user/user-datatable-page/user-datatable-page.component.ts
  src/frontend/src/app/pages/admin/user/user-key-datatable-page/user-key-datatable-page.component.ts
  src/frontend/src/app/pages/shared/bucket/bucket-lifecycle-datatable-page/bucket-lifecycle-datatable-page.component.ts
  src/frontend/src/app/pages/shared/login-page/login-page.component.ts
  src/frontend/src/app/pages/user/bucket/bucket-datatable-page/bucket-datatable-page.component.ts
  src/frontend/src/app/pages/user/object/object-datatable-page/object-datatable-page.component.ts
  src/frontend/src/app/shared/components/block-ui/block-ui.component.html
  src/frontend/src/app/shared/components/block-ui/block-ui.component.scss
  src/frontend/src/app/shared/components/block-ui/block-ui.component.spec.ts
  src/frontend/src/app/shared/components/block-ui/block-ui.component.ts
  src/frontend/src/app/shared/components/components.module.ts
  src/frontend/src/app/shared/components/page-wrapper/page-wrapper.component.ts
  src/frontend/src/app/shared/layouts/blank-layout/blank-layout.component.html
  src/frontend/src/app/shared/layouts/main-layout/main-layout.component.html
  src/frontend/src/app/shared/services/block-ui.service.spec.ts
  src/frontend/src/app/shared/services/block-ui.service.ts
  src/frontend/src/app/shared/services/rxjs-ui-helper.service.ts
  src/frontend/src/app/shared/shared.module.ts
  src/frontend/src/index.html
  src/frontend/src/scss/blockui.scss
  src/frontend/src/styles.scss
Labels: kind/quality, area/ui

#180 Fix unit test
  src/frontend/src/app/app.component.spec.ts
Labels: kind/bug, area/ui

#181 Migrate to Angular 15
  src/frontend/.browserslistrc
  src/frontend/angular.json
  src/frontend/jest.config.js
  src/frontend/package-lock.json
  src/frontend/package.json
  src/frontend/src/app/shared/components/declarative-form-modal/declarative-form-modal.component.html
  src/frontend/src/scss/bootstrap.scss
  src/frontend/tsconfig.json
Labels: kind/quality, area/ui

#184 Upgrade stylelint
  src/frontend/.stylelintrc.json
  src/frontend/package-lock.json
  src/frontend/package.json
  src/frontend/src/app/pages/admin/dashboard-page/dashboard-page.component.scss
  src/frontend/src/app/pages/user/dashboard-page/dashboard-page.component.scss
  src/frontend/src/app/pages/user/object/object-datatable-page/object-datatable-page.component.scss
  src/frontend/src/app/shared/components/breadcrumbs/breadcrumbs.component.scss
  src/frontend/src/app/shared/components/dashboard-widget/dashboard-widget.component.scss
  src/frontend/src/app/shared/components/notification-bar/notification-bar.component.scss
  src/frontend/src/app/shared/layouts/main-layout/main-layout.component.scss
  src/frontend/src/scss/bootstrap.scss
  src/frontend/src/scss/defaults/_colors.scss
Labels: kind/enhancement, area/ui

#185 UI: Unit tests non-functional in IDE
  src/frontend/package.json
  src/frontend/src/setupJest.ts
Labels: kind/bug, area/ui

#186 UI: Use checkbox instead of dropdown
  src/frontend/src/app/pages/shared/bucket/bucket-lifecycle-datatable-page/bucket-lifecycle-datatable-page.component.ts
Labels: kind/enhancement, area/ui

#188 UI: Do not display objects that have also a delete marker
  CHANGELOG.md
  src/frontend/src/app/pages/user/object/object-datatable-page/object-datatable-page.component.ts
Labels: kind/bug, area/ui

#187 improvements and restructure of cypress tests
  src/frontend/cypress/e2e/bucket.cy.ts
  src/frontend/cypress/e2e/dashboard.cy.ts
  src/frontend/cypress/e2e/login.cy.ts
  src/frontend/cypress/e2e/topbar.cy.ts
  src/frontend/cypress/support/commands.ts
Labels: kind/enhancement, area/ui

#190 The ID of radios and checkboxes is not set correct
  src/frontend/src/app/shared/components/declarative-form/declarative-form.component.html
Labels: kind/bug, area/ui

#189 UI: Object version management: Enable object delete/undelete
  CHANGELOG.md
  src/frontend/angular.json
  src/frontend/package-lock.json
  src/frontend/package.json
  src/frontend/src/app/functions.helper.spec.ts
  src/frontend/src/app/functions.helper.ts
  src/frontend/src/app/pages/shared/bucket/bucket-lifecycle-datatable-page/bucket-lifecycle-datatable-page.component.ts
  src/frontend/src/app/pages/user/object/object-datatable-page/object-datatable-page.component.html
  src/frontend/src/app/pages/user/object/object-datatable-page/object-datatable-page.component.ts
  src/frontend/src/app/pages/user/object/object-version-datatable-page/object-version-datatable-page.component.html
  src/frontend/src/app/pages/user/object/object-version-datatable-page/object-version-datatable-page.component.scss
  src/frontend/src/app/pages/user/object/object-version-datatable-page/object-version-datatable-page.component.spec.ts
  src/frontend/src/app/pages/user/object/object-version-datatable-page/object-version-datatable-page.component.ts
  src/frontend/src/app/pages/user/user-pages-routing.module.ts
  src/frontend/src/app/pages/user/user-pages.module.ts
  src/frontend/src/app/shared/components/datatable-actions/datatable-actions.component.ts
  src/frontend/src/app/shared/components/datatable/datatable.component.ts
  src/frontend/src/app/shared/components/declarative-form/declarative-form.component.html
  src/frontend/src/app/shared/components/declarative-form/declarative-form.component.ts
  src/frontend/src/app/shared/components/page-title/page-title.component.html
  src/frontend/src/app/shared/components/page-title/page-title.component.scss
  src/frontend/src/app/shared/components/tags-input/tags-input.component.ts
  src/frontend/src/app/shared/enum/icon.enum.ts
  src/frontend/src/app/shared/models/datatable-action.type.ts
  src/frontend/src/app/shared/models/declarative-form-config.type.ts
  src/frontend/src/app/shared/pipes/basename.pipe.spec.ts
  src/frontend/src/app/shared/pipes/basename.pipe.ts
  src/frontend/src/app/shared/pipes/decode-uri-component.pipe.spec.ts
  src/frontend/src/app/shared/pipes/decode-uri-component.pipe.ts
  src/frontend/src/app/shared/pipes/pipes.module.ts
  src/frontend/src/app/shared/pipes/truncate.pipe.spec.ts
  src/frontend/src/app/shared/pipes/truncate.pipe.ts
  src/frontend/src/app/shared/services/api/s3-bucket.service.ts
Labels: kind/enhancement, area/ui

#191 The ID of radios and checkboxes is not set correct
  src/frontend/src/app/shared/components/declarative-form/declarative-form.component.html
Labels: kind/bug, area/ui
